### ISSUE TITLE
Unable to update kraft caches

### ISSUE THREAD

**Issue by vaastav** [unikraft/kraft#122]
**Describe the bug**
Unable to update kraft caches

**To Reproduce**
I ran the command `kraft -v up -p kvm -m x86_64 -t helloworld helloworld`

**Expected behavior**
I expected the helloworld application to be booted properly

**Screenshots**
Here is the complete output
```
[DEBUG   ] Synchronizing cache with filesystem...
[DEBUG   ] Checking cache for staleness...
kraft caches are out-of-date. Would you like to update? [Y/n]: Y
[INFO    ] Using direct repository: https://github.com/unikraft/unikraft.git
[CRITICAL] compare() missing 1 required positional argument: 'loose'
[CRITICAL] Traceback (most recent call last):
  File "/home/vaastav/anaconda3/lib/python3.8/site-packages/kraft/cmd/list/update.py", line 82, in kraft_update
    thread.join()
  File "/home/vaastav/anaconda3/lib/python3.8/site-packages/kraft/util/threading.py", line 58, in join
    raise self.exc
  File "/home/vaastav/anaconda3/lib/python3.8/site-packages/kraft/util/threading.py", line 49, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/vaastav/anaconda3/lib/python3.8/site-packages/kraft/cmd/list/provider/github.py", line 139, in <lambda>
    target=lambda *arg: items.put(get_component_from_github(*arg)),
  File "/home/vaastav/anaconda3/lib/python3.8/site-packages/kraft/cmd/list/provider/github.py", line 252, in get_component_from_github
    dist.add_version(ManifestItemVersion(
  File "/home/vaastav/anaconda3/lib/python3.8/site-packages/kraft/manifest/manifest.py", line 252, in add_version
    if semver.compare(current_version, latest_version) > 0:
TypeError: compare() missing 1 required positional argument: 'loose'
```
If I try to not update the caches, then I see the following error

```
[DEBUG   ] Synchronizing cache with filesystem...
[DEBUG   ] Checking cache for staleness...
kraft caches are out-of-date. Would you like to update? [Y/n]: n
[WARNING ] Could not find manifest: helloworld
[ERROR   ] No manifests to download
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python 3.8 (via anaconda)

Any help would be appreciated.

**Comment by nderjung** [comment]
Hi @vaastav ,

We have now deprecated [kraft](https://github.com/unikraft/kraft) in favour of [KraftKit](https://github.com/unikraft/kraftkit). Please can you try this tool instead, you won't run into this kind of error with it.

**Comment by vaastav** [comment]
Ok thanks! I will try this next week and let you know if KraftKit works for me.
Thanks for responding.
