### ISSUE TITLE
Kraft commend returns error

### ISSUE THREAD

**Issue by gabx** [unikraft/kraft#15]
**Describe the bug**
When running `$ kraft init` or `kraft list`, output give an error.

**To Reproduce**

```
$  kraft init
kraft caches are out-of-date.  Would you like to update? [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/kraft", line 11, in <module>
    load_entry_point('kraft==0.4.0', 'console_scripts', 'kraft')()
  File "/home/gabx/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/gabx/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/gabx/.local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gabx/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gabx/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/gabx/.local/lib/python3.8/site-packages/kraft/commands/init.py", line 201, in init
    kraft_init(
  File "/home/gabx/.local/lib/python3.8/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/gabx/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/gabx/.local/lib/python3.8/site-packages/kraft/commands/init.py", line 66, in kraft_init
    update()
  File "/home/gabx/.local/lib/python3.8/site-packages/kraft/commands/list.py", line 198, in update
    org = github.get_organization(UK_GITHUB_ORG)
  File "/home/gabx/.local/lib/python3.8/site-packages/github/MainClass.py", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/home/gabx/.local/lib/python3.8/site-packages/github/Requester.py", line 320, in requestJsonAndCheck
    return self.__check(
  File "/home/gabx/.local/lib/python3.8/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
```
Same output with `kraft list`

**Desktop (please complete the following information):**
```
$  kraft --version
kraft, version 0.4.0
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
$ uname -r
5.6.5-arch3-1
$  python --version
Python 3.8.2
```

**Comment by nderjung** [comment]
Hi @gabx, have you tried the [`staging`](https://github.com/unikraft/kraft/tree/staging) branch?  Updates are pushed to this until we release `v0.5.0`.

**Comment by gabx** [comment]
No, I will give a try thus,

**Comment by gabx** [comment]
why did you close it? I haven't give a try at the staging branch yet.
